name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - '**'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          #cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Optional: golangci-lint command line arguments.
          args: -D errcheck
          # Optional: if set to true, caches will not be saved, but they may still be restored,
          #           subject to other options
          # skip-save-cache: true
