name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - '**'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          #cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: golangci-lint command line arguments.
          args: -D errcheck
